#+TITLE: AKS Pod Horizontal Scaling based on requests
#+date: <2022-09-14 Sun>
#+tags: azure, keda, containers, kubernetes

It is a common requirement to scale applications deployed on Kubernetes. This post targets on how to leverage Azure built in features to configure horizontal pod autoscaling. Usually, the infrastrucre is setup with a mointoring system such as [[https://prometheus.io/]] [prometheus] and configure custom metric scraping from the applications. However, the focus for this post is to explore the default capabilities provided by Azure platform  to achieve horizontal pod scaling.

[[https://keda.sh/]] [Keda] is an excellent opensource initiative and part of CCNF which will be used in this blog post.

Install Keda on your AKS cluster
#+begin_src shell
kubectl apply -f https://github.com/kedacore/keda/releases/download/v2.8.0/keda-2.8.0.yaml

#+end_src


Create Keda Secret, TriggerAuthetication, ScaledObject
#+begin_src shell
kubectl apply -f https://raw.githubusercontent.com/udayblog/public_cloud/main/azure/aks/keda/hpa.yml

#+end_src

Trigger query specified in the ScaledObject will monitor the requests coming to Azure Application Gateway in five minutes intervals. Once those requests exceed the threshold value which is set as 10 in the query, then HPA will scale pods.
